### ISSUE TITLE
Maybe a bug in parsing HPROF_GC_CLASS_DUMP

### ISSUE THREAD

**Issue by tokuhirom** [google/hprof-parser#5]
Every constant pool contains a `constant pool index`.
http://hg.openjdk.java.net/jdk/jdk/file/4b49cfba69fe/src/hotspot/share/services/heapDumper.cpp#l240

But the parser doesn't read it.
https://github.com/google/hprof-parser/blob/master/parser/parser.go#L426

It looks like a bug.

**Comment by draftcode** [comment]
Yeah. It's a bug. I'll add a field.
